# Generated by Django 4.0.2 on 2022-02-07 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmenAman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('mobile_num', models.CharField(max_length=11, verbose_name='رقم الموبايل')),
                ('mobile_num2', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم الموبايل 2')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='الايميل')),
                ('name_area', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسم المنطقة')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القطعة-الخدمة')),
                ('describe_item', models.TextField(blank=True, null=True, verbose_name='وصف القطعة')),
                ('type_parent', models.CharField(choices=[('دهانات', 'دهانات'), ('قطع غيار', 'قطع غيار'), ('تركيبات', 'تركيبات'), ('كهرباء', 'كهرباء'), ('زجاج', 'زجاج'), ('اكسسوارات السيكوريت', 'اكسسوارات السيكوريت'), ('تكييف', 'تكييف'), ('نقل', 'نقل'), ('معاينة', 'معاينة'), ('رفع مقاسات', 'رفع مقاسات'), ('ستاندات', 'ستاندات'), ('علب خشبية', 'علب خشبية'), ('جيبسون بورد', 'جيبسون بورد'), ('كلادينج', 'كلادينج'), ('الباب الصاج', 'الباب الصاج'), ('ستانلس', 'ستانلس')], max_length=100, verbose_name='النوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Items/', verbose_name='صورة القطعة')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم الاول')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللقب')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم التليفون')),
                ('phone_number2', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم التليفون 2')),
                ('addres', models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='المنقطة')),
                ('mailo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ايميل (بالشركة)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profiles/', verbose_name='صورة شخصية')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='المسمى الوظيفى')),
                ('pos_in_store', models.CharField(blank=True, choices=[('aman_admin', 'Admin'), ('aman_manager', 'Manager'), ('quality', 'Quality'), ('technical', 'Technical'), ('staff', 'staff')], max_length=50, null=True, verbose_name='صفته بالموقع')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الفرع')),
                ('image_store', models.ImageField(blank=True, null=True, upload_to='Stores/MainPic', verbose_name='صورة الفرع')),
                ('monthly_visited', models.BooleanField(blank=True, default=True, null=True, verbose_name='زيارة شهرية')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='يعمل')),
                ('name_area', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسم المنطقة')),
                ('line', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط السير')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة')),
                ('address_store', models.CharField(blank=True, max_length=1000, null=True, verbose_name='العنوان')),
                ('location_store', models.CharField(blank=True, max_length=1000, null=True, verbose_name='الموقع')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('admen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aman.admenaman', verbose_name='ادمين الفرع حاليا')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(blank=True, choices=[('شهرية', 'شهرية'), ('طارئة', 'طارئة'), ('شهرية-تكميلية', 'شهرية-تكميلية'), ('معاينة', 'معاينة')], max_length=100, null=True, verbose_name='نوع الزيارة')),
                ('short_desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='ملخص المشكلة')),
                ('describe_proplem', models.TextField(blank=True, max_length=3000, null=True, verbose_name='وصف المشكلة')),
                ('done', models.BooleanField(default=False)),
                ('argent', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='وقت تقديم الطلب')),
                ('date_visit', models.DateTimeField(blank=True, null=True, verbose_name='موعد الزيارة')),
                ('content', models.ManyToManyField(blank=True, related_name='items', to='aman.Item', verbose_name='الوحدة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.admenaman', verbose_name='انشاء بواسطة')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.profile', verbose_name='اصلاح بواسطة')),
                ('send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sendby', to='aman.profile', verbose_name='ارسال بواسطة')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.store', verbose_name='الفرع')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='tag',
            field=models.ManyToManyField(blank=True, to='aman.Tags', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stores',
            field=models.ManyToManyField(blank=True, to='aman.Store', verbose_name='الفروع المسئول عنها'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FixRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=200, verbose_name='وصف قصير للمشكلة')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='تايخ الطلب')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='اخر تعديل')),
                ('monthly_visited', models.BooleanField(default=True, verbose_name='مع الزيارة الشهرية')),
                ('emergency', models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Postpone', 'Postpone')], max_length=100, null=True, verbose_name='درجة الأهمية')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('admen_aman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.admenaman', verbose_name='الادمن المسئول')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.store', verbose_name='الفرع')),
            ],
        ),
        migrations.AddField(
            model_name='admenaman',
            name='tag',
            field=models.ManyToManyField(blank=True, to='aman.Tags', verbose_name='Tag'),
        ),
    ]
