# Generated by Django 4.0.2 on 2022-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pos_in_store',
            field=models.CharField(blank=True, choices=[('aman_admin', 'Admin'), ('aman_manager', 'Manager'), ('quality', 'Quality'), ('technical', 'Technical'), ('staff', 'staff'), ('elnasr_admin', 'ElNasr'), ('defaultt', 'defaultt')], max_length=50, null=True, verbose_name='صفته بالموقع'),
        ),
    ]
