# Generated by Django 4.0.2 on 2022-02-08 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aman', '0002_alter_profile_pos_in_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_admin', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='ادمين الفرع'),
        ),
        migrations.AddField(
            model_name='store',
            name='user_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_staff', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='موظف الفرع'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pos_in_store',
            field=models.CharField(blank=True, choices=[('aman_admin', 'Admin'), ('aman_manager', 'Manager'), ('quality', 'Quality'), ('technical', 'Technical'), ('staff', 'staff'), ('elnasr_admin', 'ElNasr'), ('default', 'default')], max_length=50, null=True, verbose_name='صفته بالموقع'),
        ),
    ]
