# Generated by Django 4.0.2 on 2022-02-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0003_store_user_admin_store_user_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Visits/')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.store', verbose_name='الفرع')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.visit', verbose_name='الزيارة')),
            ],
        ),
    ]
