# Generated by Django 4.0.2 on 2022-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0005_store_user_admin_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pos_in_store',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Quality', 'Quality'), ('Technical', 'Technical'), ('Sales', 'Sales'), ('ElNasr', 'ElNasr'), ('default', 'default')], max_length=50, null=True, verbose_name='صفته بالموقع'),
        ),
    ]
