# Generated by Django 4.0.2 on 2022-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0006_alter_profile_pos_in_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
