# Generated by Django 4.0.2 on 2022-02-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0008_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.visit', verbose_name='الزيارة'),
        ),
    ]
