# Generated by Django 4.0.2 on 2022-02-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0011_visit_faults_alter_fault_item_imagefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fault_visit', to='aman.visit', verbose_name='الزيارة'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='faults',
            field=models.ManyToManyField(blank=True, related_name='visit_faults', to='aman.Fault', verbose_name='اصلاح بواسطة'),
        ),
    ]
