# Generated by Django 4.0.2 on 2022-02-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0014_alter_fault_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='وقت ارسال المشكلة'),
        ),
        migrations.AddField(
            model_name='fault',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='aman.profile', verbose_name='ارسال بواسطة'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imagefault',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.fault', verbose_name='العطل'),
        ),
    ]
