# Generated by Django 4.0.2 on 2022-02-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0015_fault_created_at_fault_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='faults',
        ),
    ]
