# Generated by Django 4.0.2 on 2022-02-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0017_rename_user_admin_all_store_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.profile', verbose_name='اصلاح بواسطة'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='send_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendby', to='aman.profile', verbose_name='ارسال بواسطة'),
        ),
    ]
