# Generated by Django 4.0.2 on 2022-02-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0018_alter_visit_fixed_by_alter_visit_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='faults',
            field=models.ManyToManyField(blank=True, related_name='proplems', to='aman.Fault', verbose_name='الأعطال'),
        ),
    ]
