# Generated by Django 4.0.2 on 2022-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0019_visit_faults'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='visitat', to='aman.Visit', verbose_name='الزيارات'),
        ),
    ]
