# Generated by Django 4.0.2 on 2022-02-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0020_store_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.store'),
        ),
    ]
