# Generated by Django 4.0.2 on 2022-02-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0021_fault_belong_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='content',
        ),
    ]
