# Generated by Django 4.0.2 on 2022-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0022_remove_visit_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='argent',
            field=models.BooleanField(default=False, verbose_name='طارئ'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='done',
            field=models.BooleanField(default=False, verbose_name='انتهاء الزيارة'),
        ),
    ]
