# Generated by Django 4.0.2 on 2022-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0023_alter_visit_argent_alter_visit_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='status',
            field=models.BooleanField(verbose_name='تم الاصلاح'),
        ),
    ]
