# Generated by Django 4.0.2 on 2022-02-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0024_alter_fault_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت اصلاح المشكلة'),
        ),
    ]
