# Generated by Django 3.2.9 on 2022-02-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0025_fault_fixed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='active',
            field=models.BooleanField(default=False, verbose_name='اظهار العطل'),
        ),
        migrations.AddField(
            model_name='fault',
            name='active_tosend',
            field=models.BooleanField(blank=True, default=True, verbose_name='الموافقة على الارسال'),
        ),
        migrations.AddField(
            model_name='fault',
            name='approved_to_repair',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='fault',
            name='need_to_approve',
            field=models.BooleanField(blank=True, default=False, verbose_name='اصلاح يحتاج الى موافقة'),
        ),
    ]
