# Generated by Django 3.2.9 on 2022-02-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0026_auto_20220213_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='active_tosend',
            field=models.BooleanField(blank=True, default=True, verbose_name='ارسال العطل الى الصيانة'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='approved_to_repair',
            field=models.BooleanField(blank=True, default=False, verbose_name='تم الموافقة على الاصلاح'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.store', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='aman.profile', verbose_name='انشاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ملخص المشكلة'),
        ),
    ]
