# Generated by Django 3.2.9 on 2022-02-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0027_auto_20220214_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
