# Generated by Django 3.2.9 on 2022-02-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0028_visit_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='describe_item',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='وصف القطعة'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_parent',
            field=models.CharField(choices=[('دهانات', 'دهانات'), ('قطع غيار', 'قطع غيار'), ('تركيبات', 'تركيبات'), ('كهرباء', 'كهرباء'), ('زجاج', 'زجاج'), ('اكسسوارات السيكوريت', 'اكسسوارات السيكوريت'), ('تكييف', 'تكييف'), ('نقل', 'نقل'), ('معاينة', 'معاينة'), ('رفع مقاسات', 'رفع مقاسات'), ('ستاندات', 'ستاندات'), ('علب خشبية', 'علب خشبية'), ('جيبسون بورد', 'جيبسون بورد'), ('كلادينج', 'كلادينج'), ('الباب الصاج', 'الباب الصاج'), ('ستانلس', 'ستانلس'), ('سيراميك ورخام', 'سيراميك ورخام')], max_length=100, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
