# Generated by Django 4.0.2 on 2022-02-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0029_auto_20220215_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='StoreUnits/', verbose_name='صورة الوحدة')),
                ('parts', models.ManyToManyField(blank=True, to='aman.Item', verbose_name='قطع غيار بالوحدة')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.store', verbose_name='الفرع')),
            ],
        ),
    ]
