# Generated by Django 4.0.2 on 2022-02-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0030_storeunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeunit',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='storeunit',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='OrderStoreUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_fixed', models.DateField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('type_order', models.CharField(blank=True, max_length=150, null=True, verbose_name='نوع الطلب')),
                ('from_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.store', verbose_name=' الفرع المنقول منه')),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.storeunit', verbose_name='الفرع')),
            ],
        ),
    ]
