# Generated by Django 4.0.2 on 2022-02-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0031_storeunit_category_alter_storeunit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeunit',
            name='store',
        ),
        migrations.AddField(
            model_name='orderstoreunit',
            name='to_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.store', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='orderstoreunit',
            name='from_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_store', to='aman.store', verbose_name=' الفرع المنقول منه'),
        ),
    ]
