# Generated by Django 4.0.2 on 2022-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0035_imagefault_after_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefault',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
