# Generated by Django 4.0.2 on 2022-02-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0036_imagefault_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstoreunit',
            name='fault',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.fault'),
        ),
        migrations.AlterField(
            model_name='orderstoreunit',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aman.storeunit', verbose_name='الوحدة'),
        ),
    ]
