# Generated by Django 4.0.2 on 2022-02-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0037_orderstoreunit_fault_alter_orderstoreunit_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstoreunit',
            name='unit',
        ),
    ]
