# Generated by Django 4.0.2 on 2022-02-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0038_remove_orderstoreunit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstoreunit',
            name='store_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.storeunit'),
        ),
    ]
