# Generated by Django 4.0.2 on 2022-02-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0039_orderstoreunit_store_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstoreunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aman.profile'),
        ),
    ]
