# Generated by Django 4.0.2 on 2022-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0040_orderstoreunit_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstoreunit',
            options={'managed': True, 'verbose_name': 'Order Units', 'verbose_name_plural': 'Orders Units'},
        ),
        migrations.AddField(
            model_name='orderstoreunit',
            name='items',
            field=models.ManyToManyField(blank=True, to='aman.Item', verbose_name='اصلاحات بالوحدة'),
        ),
    ]
