# Generated by Django 4.0.2 on 2022-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0042_fault_action_to_fault_fault_status_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='choices_el_status',
            field=models.CharField(choices=[('FIX', 'Send'), ('SID', 'Fixed'), ('CHK', 'Checked'), ('SUS', 'Suspended'), ('CNL', 'Cancelled')], default='FIX', max_length=3),
        ),
        migrations.AlterField(
            model_name='fault',
            name='action_to_fault',
            field=models.CharField(choices=[('send', 'send'), ('check', 'check'), ('repair', 'repair'), ('finish', 'finish')], default='send', max_length=100, verbose_name='الاجراء المتخذ'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='status_choice',
            field=models.CharField(choices=[('sent', 'sent'), ('checked', 'checked'), ('fixed', 'Fixed'), ('reviewed', 'reviewed')], default='sent', max_length=120, verbose_name='اختيارات الحالة'),
        ),
    ]
