# Generated by Django 4.0.2 on 2022-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0043_fault_choices_el_status_alter_fault_action_to_fault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='choices_el_status',
            field=models.CharField(choices=[('SID', 'Send'), ('FIX', 'Fixed'), ('CHK', 'Checked'), ('SUS', 'Suspended'), ('CNL', 'Cancelled')], default='SID', max_length=3),
        ),
    ]
