# Generated by Django 4.0.2 on 2022-02-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aman', '0044_alter_fault_choices_el_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefault',
            name='describ',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='choices_el_status',
            field=models.CharField(choices=[('SID', 'Send'), ('FIX', 'Fixed'), ('CHK', 'Checked'), ('SUS', 'Suspended'), ('CNL', 'Cancelled')], default='SID', max_length=33),
        ),
    ]
